import React, { useState } from 'react';
import { X, Download, Image, FileText, Globe, Check } from 'lucide-react';
import { Dataset } from '../types';
import { resolveCurveColor } from '../core/colors';
import { escapeCsvField, sanitizeFileName } from '../core/mathUtils';

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function escapeScriptJson(data: any): string {
  return JSON.stringify(data).replace(/</g, '\\u003c');
}

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  datasets: Dataset[];
  activeDatasetId: string | null;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  isOpen,
  onClose,
  datasets,
  activeDatasetId,
}) => {
  const [exportType, setExportType] = useState<'csv' | 'html' | 'json'>('csv');
  const [downloadSuccess, setDownloadSuccess] = useState(false);

  if (!isOpen) return null;

  const currentDataset = datasets.find((d) => d.id === activeDatasetId) || datasets[0] || null;

  const handleExport = () => {
    if (!currentDataset) return;

    let mimeType = 'text/plain';
    let fileExt = 'txt';
    let fileContent = '';

    if (exportType === 'csv') {
      mimeType = 'text/csv';
      fileExt = 'csv';
      const cols = currentDataset.columns;
      const header = cols.map(escapeCsvField).join(',');
      const rows: string[] = [];
      for (let i = 0; i < currentDataset.rowCount; i++) {
        rows.push(cols.map((c) => escapeCsvField(currentDataset.data[c]?.[i] ?? '')).join(','));
      }
      fileContent = [header, ...rows].join('\n');
    } else if (exportType === 'json') {
      mimeType = 'application/json';
      fileExt = 'json';
      fileContent = JSON.stringify(
        {
          datasetName: currentDataset.name,
          rowCount: currentDataset.rowCount,
          columns: currentDataset.columns,
          data: currentDataset.data,
          stats: currentDataset.stats,
          metadata: currentDataset.metadata,
        },
        null,
        2
      );
    } else if (exportType === 'html') {
      mimeType = 'text/html';
      fileExt = 'html';

      const xData = currentDataset.data[currentDataset.selectedX] || [];
      const traces = currentDataset.selectedY.map((yCol, yIdx) => {
        const yData = currentDataset.data[yCol] || [];
        const color = resolveCurveColor(currentDataset, yCol, yIdx);
        const width = currentDataset.seriesStyles?.[yCol]?.lineWidth || 2;
        return {
          x: xData,
          y: yData,
          mode: 'lines',
          name: yCol,
          line: { color, width },
        };
      });

      const safeDatasetName = escapeHtml(currentDataset.name || 'Dataset');
      const tracesJson = escapeScriptJson(traces);
      const xAxisTitleJson = escapeScriptJson(currentDataset.selectedX || 'X');

      fileContent = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${safeDatasetName} - FDV Interactive Report</title>
  <script src="https://cdn.plot.ly/plotly-2.35.2.min.js"></script>
  <style>
    body { margin: 0; background: #121316; color: #e1e4e8; font-family: -apple-system, BlinkMacSystemFont, sans-serif; display: flex; flex-direction: column; height: 100vh; }
    header { padding: 16px 24px; border-bottom: 1px solid #2e323e; background: #181a20; }
    h1 { margin: 0; font-size: 18px; font-weight: 600; color: #fff; }
    #plot { flex: 1; width: 100%; height: calc(100vh - 70px); }
  </style>
</head>
<body>
  <header>
    <h1>${safeDatasetName} (FDV Export)</h1>
    <div style="font-size: 12px; color: #8b949e; margin-top: 4px;">Generated by Flexible Data Viewer • ${currentDataset.rowCount} points</div>
  </header>
  <div id="plot"></div>
  <script>
    const traces = ${tracesJson};
    Plotly.newPlot('plot', traces, {
      paper_bgcolor: '#121316',
      plot_bgcolor: '#121316',
      margin: { l: 60, r: 30, t: 30, b: 50 },
      xaxis: { title: ${xAxisTitleJson}, gridcolor: '#22252e', linecolor: '#2e323e', tickfont: { color: '#8b949e' } },
      yaxis: { title: 'Intensity / Value', gridcolor: '#22252e', linecolor: '#2e323e', tickfont: { color: '#8b949e' } }
    }, { responsive: true });
  </script>
</body>
</html>`;
    }

    // Trigger download
    const blob = new Blob([fileContent], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    const safeDownloadName = sanitizeFileName(currentDataset.name);
    link.download = `${safeDownloadName}_export.${fileExt}`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    setDownloadSuccess(true);
    setTimeout(() => {
      setDownloadSuccess(false);
      onClose();
    }, 1200);
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4 select-none animate-fade-in">
      <div className="bg-[#181a20] border border-[#2a2d37] rounded-2xl w-full max-w-md overflow-hidden shadow-2xl">
        {/* Header */}
        <div className="p-4 border-b border-[#2a2d37] flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Download className="w-5 h-5 text-[#00adb5]" />
            <h3 className="font-semibold text-sm text-white">Export Dataset & Plots</h3>
          </div>
          <button onClick={onClose} className="p-1 hover:bg-[#2a2d37] rounded text-[#8b949e] hover:text-white">
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Content */}
        <div className="p-5 space-y-4 text-xs">
          {currentDataset && (
            <div className="bg-[#121316] p-3 rounded-lg border border-[#2a2d37] flex items-center justify-between">
              <span className="text-[#8b949e]">Target Dataset:</span>
              <span className="text-white font-medium">{currentDataset.name}</span>
            </div>
          )}

          {/* Export Options */}
          <div className="space-y-2">
            <label className="text-[#9ca3af] font-medium">Export Format</label>
            <div className="grid grid-cols-3 gap-2">
              <button
                onClick={() => setExportType('csv')}
                className={`flex flex-col items-center justify-center p-3 rounded-lg border text-center transition-all ${
                  exportType === 'csv'
                    ? 'bg-[#242731] border-[#00adb5] text-white shadow-sm'
                    : 'bg-[#14161b] border-[#2a2d37] text-[#8b949e] hover:bg-[#1a1c22]'
                }`}
              >
                <FileText className="w-5 h-5 mb-1 text-[#00adb5]" />
                <span className="font-medium">CSV Table</span>
                <span className="text-[10px] text-[#6b7280]">Processed data</span>
              </button>

              <button
                onClick={() => setExportType('html')}
                className={`flex flex-col items-center justify-center p-3 rounded-lg border text-center transition-all ${
                  exportType === 'html'
                    ? 'bg-[#242731] border-[#00adb5] text-white shadow-sm'
                    : 'bg-[#14161b] border-[#2a2d37] text-[#8b949e] hover:bg-[#1a1c22]'
                }`}
              >
                <Globe className="w-5 h-5 mb-1 text-[#2196f3]" />
                <span className="font-medium">Interactive HTML</span>
                <span className="text-[10px] text-[#6b7280]">Standalone report</span>
              </button>

              <button
                onClick={() => setExportType('json')}
                className={`flex flex-col items-center justify-center p-3 rounded-lg border text-center transition-all ${
                  exportType === 'json'
                    ? 'bg-[#242731] border-[#00adb5] text-white shadow-sm'
                    : 'bg-[#14161b] border-[#2a2d37] text-[#8b949e] hover:bg-[#1a1c22]'
                }`}
              >
                <FileText className="w-5 h-5 mb-1 text-[#ff9800]" />
                <span className="font-medium">JSON</span>
                <span className="text-[10px] text-[#6b7280]">Raw object</span>
              </button>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 bg-[#14161b] border-t border-[#2a2d37] flex items-center justify-end gap-2">
          <button
            onClick={onClose}
            className="px-4 py-2 bg-[#20232c] hover:bg-[#2a2d37] text-white rounded-lg text-xs font-medium transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={handleExport}
            className="flex items-center gap-1.5 px-4 py-2 bg-[#00adb5] hover:bg-[#00c4cd] text-black rounded-lg text-xs font-semibold shadow-lg shadow-[#00adb5]/20 transition-all active:scale-95"
          >
            {downloadSuccess ? <Check className="w-4 h-4" /> : <Download className="w-4 h-4" />}
            <span>{downloadSuccess ? 'Downloaded!' : 'Download Export'}</span>
          </button>
        </div>
      </div>
    </div>
  );
};
